package io.openems.edge.meter.mqtt.shelly;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;
import io.openems.edge.common.type.Phase.SinglePhase;

@ObjectClassDefinition(//
		name = "Meter MQTT Shelly", //
		description = "Implements one em1:x channel of a Shelly Gen2 RPC device, received via MQTT.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "MQTT-Bridge-ID", description = "ID of the Bridge.Mqtt Component of this device")
	String mqtt_id() default "mqtt0";

	@AttributeDefinition(name = "Topic prefix", description = "The device's MQTT topic prefix, usually equal to its MQTT username, e.g. 'shelly01'")
	String topicPrefix();

	@AttributeDefinition(name = "Channel", description = "Shelly EM1 channel id. Usually 0 or 1.")
	int channel() default 0;

	@AttributeDefinition(name = "Phase", description = "Which phase is measured by this channel?")
	SinglePhase phase() default SinglePhase.L1;

	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Invert Power", description = "Inverts power and current values, swaps production and consumption energy. Use this to fix reversed CT-clamp wiring.")
	boolean invert() default false;

	@AttributeDefinition(name = "Add to Sum", description = "Include this Meter in the system-wide Sum (_sum/GridActivePower etc.)? Default false, because this Meter usually represents a third-party/community participant (e.g. a vZEV member) rather than a physically local circuit.")
	boolean addToSum() default false;

	@AttributeDefinition(name = "MQTT target filter", description = "This is auto-generated by 'MQTT-Bridge-ID'.")
	String Mqtt_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter MQTT Shelly [{id}]";

}
