
package io.openems.edge.meter.virtual.gate;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Meter Virtual Gate", //
		description = """
				This is a virtual meter that passes through the values of another meter, but reports \
				zero as long as the configured Energy Storage System's State-of-Charge is at or below \
				a configured reserve threshold. \
				Example use-case: exclude a neighbour's grid meter from a combined ZEV grid target once \
				the battery's SoC drops to a reserve that must stay available for own consumption.""")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "Grid (=default), Production, Consumption")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Meter-ID", description = "Component-ID of the meter to be gated")
	String meter_id();

	@AttributeDefinition(name = "Ess-ID", description = "Component-ID of the Energy Storage System providing the State-of-Charge")
	String ess_id();

	@AttributeDefinition(name = "Reserve SoC [%]", description = "At or below this State-of-Charge the gated meter reports zero instead of its real value")
	int reserveSoc() default 30;

	@AttributeDefinition(name = "Add to Sum?", description = "Should the data of this meter be added to the Sum?")
	boolean addToSum() default false;

	@AttributeDefinition(name = "Meter target filter", description = "This is auto-generated by 'Meter-ID'.")
	String meter_target() default "(enabled=true)";

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter Virtual Gate [{id}]";

}
