package io.openems.edge.meter.mqtt.whatwatt;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Meter MQTT WhatWatt", //
		description = "Implements a whatwatt Go smart-meter adapter, received via MQTT.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter1";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "MQTT-Bridge-ID", description = "ID of the Bridge.Mqtt Component of this device")
	String mqtt_id() default "mqtt0";

	@AttributeDefinition(name = "Topic", description = "The whatwatt Go's configured MQTT publish topic, e.g. 'zevplus/c0001/wwg/meter'")
	String topic();

	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Add to Sum", description = "Include this Meter in the system-wide Sum (_sum/GridActivePower etc.)? Default false, because this Meter usually represents a third-party/community participant (e.g. a vZEV member) rather than the own physical grid connection.")
	boolean addToSum() default false;

	@AttributeDefinition(name = "MQTT target filter", description = "This is auto-generated by 'MQTT-Bridge-ID'.")
	String Mqtt_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter MQTT WhatWatt [{id}]";

}
