package io.openems.edge.controller.ess.socreserveestimator;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Controller Ess Soc Reserve Estimator", //
		description = """
				Calculates a dynamic minimum State-of-Charge reserve from consumption and production \
				forecasts: enough energy is kept reserved to cover the expected own consumption until \
				PV production picks up again, plus a safety margin and a fixed end-of-window reserve \
				for battery health and blackout protection. Publishes the result as a Channel for other \
				components (e.g. Meter.Virtual.Gate) to consume. Does not set any power constraints on \
				the Ess itself.""")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlSocReserveEstimator0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Ess-ID", description = "Component-ID of the Energy Storage System providing the capacity")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Production Threshold [W]", description = "Forecasted production at or above this value counts as 'PV is producing again' and marks the end of the reserve window")
	int productionThreshold() default 1000;

	@AttributeDefinition(name = "Safety Margin", description = "Extra fraction added on top of the forecasted energy need, to compensate for forecast errors (0.1 = +10%)")
	double safetyMargin() default 0.1;

	@AttributeDefinition(name = "End-SoC Reserve [%]", description = "Fixed minimum SoC that should still remain once the reserve window ends, independent of forecast accuracy (battery health / blackout reserve)")
	int endSocReserve() default 10;

	@AttributeDefinition(name = "Fallback Horizon Time", description = "Local time (HH:mm) used as the reserve window end if the production forecast is missing or never reaches the threshold within 24h")
	String fallbackHorizonTime() default "08:00";

	@AttributeDefinition(name = "Min-SoC Clamp Low [%]", description = "The calculated Min-SoC is never reported below this value")
	int minSocClampLow() default 5;

	@AttributeDefinition(name = "Min-SoC Clamp High [%]", description = "The calculated Min-SoC is never reported above this value")
	int minSocClampHigh() default 80;

	@AttributeDefinition(name = "Ess target filter", description = "This is auto-generated by 'Ess-ID'.")
	String ess_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Controller Ess Soc Reserve Estimator [{id}]";

}
